worldcoin/hubble-commander

- commander/registered_tokens.go
This PR reverts changes from #432. Turns out that this check is unnecessary because we don't need to read anything from the calldata.
> Remove redundant check from tokens sync

- api/get_commitment_proof_test.go
- api/get_commitment_test.go
- api/get_network_info_test.go
- api/handle_create2transfer.go
- api/handle_mass_migration.go
- api/handle_transfer.go
- commander/executor/create_commitments_test.go
- commander/executor/execute_c2ts_test.go
- commander/executor/execute_transfers_test.go
- commander/executor/revert_batches_test.go
- commander/mm_batches_test.go
- commander/new_block_test.go
- commander/rollup_test.go
- commander/syncer/txs_sync_transfer_batch_test.go
- commander/txs_batches_test.go
- models/generic_transaction.go
- models/stored/tx_receipt.go
- storage/create2transfer.go
- storage/create2transfer_test.go
- storage/mass_migration.go
- storage/mass_migration_test.go
- storage/stored_transaction_test.go
- storage/transaction.go
- storage/transaction_test.go
- storage/transfer.go
- storage/transfer_test.go
While working on [PRO-38](https://linear.app/worldcoin/issue/PRO-38/change-storedtx-and-storedtxreceipt-into-pendingtx-and-minedtx-tables) I noticed some code duplication, opening a quick PR to remove it.
This should be much easier to review if you look at the individual commits.
TODO:
- The create2 case also included a check for `t.ToStateID`, which I don't think is necessary, but I want to go back and make sure nothing relies on that behavior (which this PR drops)
- There are now some duplicated tests which should be deduplicated.
> Drop Some Duplicated Code

- eth/dispute_transition.go
- eth/utils.go
This PR renames and makes `GetRevertMessage` public. On multiple occasions now, this method was useful for debugging failing E2E tests, however we always copied its content to create a temporary function in E2E test file that was immediately deleted after fulfilling its purpose. I believe that this change will shorten the time needed to debug E2E tests in the future.
> Make GetRevertMessage method public

- storage/account.go
- storage/batch.go
This change results in faster batch creation for `create2transfer` transactions. The difference:
- `GetFirstPubKeyID` before the change, took `~8%` of the C2T benchmark test
- `GetFirstPubKeyID` after the change, took `~0.04%` of the C2T benchmark test
> Replace bh.FindOne with bh.Find.Limt(1)

- storage/stored_transaction.go
- storage/transaction.go
Here is a semgrep rule which finds all of these:
```yaml
rules:
- id: execute-in-transaction
languages:
- go
message: Use of outer transaction inside transaction
patterns:
- pattern-inside: $OUTER.executeInTransaction(...)
- pattern: $OUTER.$ATTR
- pattern-not: $OUTER.executeInTransaction
severity: ERROR
```
> bug - consistent transaction usage

- .github/workflows/build-test-deploy.yml
- deploy/hubble/templates/ebs-volume.yaml
- deploy/hubble/templates/ebs-wipe.yaml
- deploy/hubble/templates/statefulset.yaml
- deploy/hubble/values.yaml
(PR is deployed on stage)
- add statically provisioned volume for persistent storage
- add K8s Job (as Helm pre-install hook) for cleanup volume **if necessary** (for now its manual step)
- cleanup is done step-by-step: first Helm starts Job objects (as pre-install hook), after finish Helm starts the rest of deployment. Thanks to this we can wipe data on disk, **before** start application. (More info below)
- update golangci-lint to newer version and increase timeout -> because it failed with the previous settings
Default deployment creates `PersistentVolume` and `PersistentVolumeClaim` connected with existing EBS Volume (provisioned via Terraform). It's connected using Retain policy, so create/remove EBS is possible only via Terraform.
Wipe deployment uses Helm feature: …
> Deployment volume

- deploy/hubble/templates/statefulset.yaml
Related to PRO-267
```
ad.datadoghq.com/{{ .Chart.Name }}.instances: |
[
{
"openmetrics_endpoint": "http://%%host%%:2112/metrics",
"namespace": "{{ .Release.Namespace }}",
"metrics": ["hubble_*"]
}
]
```
- `2112` port is defined [by application](https://github.com/worldcoin/hubble-commander/blob/prometheus-metrics-to-datadog/config/config.go#L22), same as `/metrics` path
-  metrics `hubble_*` are taken from output `curl http://<CONTAINER_IP>:2112/metrics` - all metrics starts with this prefix, so we are getting all metrics to Datadog
> Add prometheus metrics for Datadog

- docs/debugging_tips.md
I wonder if this looks right, or if there's an easier way that I missed.
> Add a document so I can remember how to debug rollup loop crashes

- commander/new_block_test.go
- commander/sync_stake_withdrawals_test.go
Previously the rollup loop would crash and emit a stack trace even though the test had passed and everything had gone as expected, now the test output is cleaner.
> Cleanly shutdown rollup loop in tests

- commander/rollup.go
- db/db.go
- storage/account_tree.go
- storage/batch.go
- storage/database.go
- storage/deposit.go
- storage/deposit_sub_tree.go
- storage/initialize_index.go
- storage/pending_stake_withdrawal.go
- storage/registered_spoke.go
- storage/state_tree.go
- storage/stored_commitment.go
- storage/stored_transaction.go
- At the end of the commander tests the rollup loop often crashes.
Previously the stack trace it crashed with was very uninformative,
this change fixes the stack trace and tells us exactly where the loop
is crashing (this change does not fix the crashes, which are probably
unclean shutdowns)
- We were checking for exact error equality in a bunch of places which
prevented us from wrapping any errors as they entered our control. Now
we use errors.Is in many more places. errors.Is does the correct thing
when we give it wrapped errors.
> Improve error handling

- db/encoder.go
- models/stored/state_leaf.go
- models/stored/state_leaf_test.go
- storage/state_leaf.go
- storage/state_tree.go
Puled from the migrate-0.4.0 branch, badger uses reflection when deciding which key to store each record under. By renaming stored.StateLeaf -> stored.FlatStateLeaf our database schema matches the v0.4.0 database schema.
> Rename stored.StateLeaf to support exporting from an older database.

- .github/workflows/build-test-deploy.yml
We recreated the new EKS cluster with security improvements.
Before merge:
> B-619 ci: Use a new cluster for staging

- go.mod
- go.sum
Using a fork of ristretto under my name: https://github.com/lithp/ristretto/releases/tag/v0.1.0-hotfix
This is v0.1.0 with one additional cherry-picked commit: https://github.com/lithp/ristretto/commit/4c2f84d7905791d8d48e73cc6cd8fae695644d44
Long-term we might want to fork ristretto into the worldcoin org
> Use a custom fork of ristretto, add arm64 linux support

- e2e/geth-data/fundSecondAccount.sh
Fix for regression introduced by: https://github.com/ethereum/go-ethereum/pull/24751
> Fund account script: Move position argument after flags

- api/handle_transfer_test.go
- commander/chain_spec.go
- commander/chain_spec_test.go
- commander/commander.go
- commander/commander_test.go
- commander/deploy.go
- commander/new_block_test.go
- docs/badger/data_structures.md
- eth/test_client.go
- models/chain_state.go
- models/chain_state_test.go
- storage/block_number.go
- storage/block_number_test.go
- storage/chain_state_test.go
While syncing, every time we process a new block we update the
SyncedBlock record. When a row is updated in Badger the entire row is
written to disk. Previously, this meant that every time we injested a
new block we wrote a copy of the entire ChainState record to disk. This
caused massive write amplification for deployments with a large genesis.
SyncedBlock is now stored separately, eliminating the worst of the write
amplification.
> Extract SyncedBlock from ChainState record

- .github/workflows/build-test-deploy.yml
Hubble can take a while to startup, lets remove waiting done via --atomic.
> Remove --atomic from helm deployment for prod

- api/get_user_state_test.go
- storage/mempool.go
Addresses the first half of PRO-298, after this is merged new txn receivers will no longer be given incorrect states. A follow-up PR will fix the incorrect states which have already been set.
> API should not add fee to receiver balance

- api/admin/api.go
- api/admin/mempool.go
- api/mempool_test.go
- models/dto/recompute_pending_state.go
- storage/mempool.go
These two methods are sufficient for fixing the current incorrect state in Hubble as well as future problems with the state which might arise:
- `admin_getPendingStates(startStateID, pageSize)` returns the pending states, and supports pagination in case there are too many accounts to return in a single request.
- `admin_recomputePendingState(stateID, mutate)` processes the mempool, starting from the batched state, and returns both the current pending state and the correct pending state. If `mutate` is true then it updates the current pending state. It opens a transaction and will be serialized w.r.t any `hubble_sendTransaction` handlers.
There are tests and I've also tested it against a local hubble. The lint gh action is currently broken, ignore the failure, the linter is happy with this …
> Add `admin_` methods for fixing broken pending states

- .github/workflows/build-test-deploy.yml
**problem**: every run of golangci-lint fails [what might be](https://github.com/golangci/golangci-lint/issues/576) an out-of-memory error.
**origin**: as far as I can tell lint broke because of a lack of nix, the last succeeding lint run was [here](https://github.com/worldcoin/hubble-commander/actions/runs/2800118391/jobs/4415003450), it ran lint using go1.18.4. [the next lint run](https://github.com/worldcoin/hubble-commander/actions/runs/2843057705/jobs/4501623310) happened about an hour later and used the same version of golangci-lint, we specify v1.45.2, but it switched to using go1.19, something we did not pin down. Ever since this run golangci-lint has been failing.
**proposed solution**: first merge this PR, then merge all outstanding work, then merge …
> temporarily disable lint

- commander/commander.go
- commander/new_block.go
- commander/rollup.go
- config/config.go
- config/model.go
- deploy/hubble/templates/statefulset.yaml
`export HUBBLE_SAFE_MODE=true` will cause Hubble to only start the API and some background workers. It will not attempt to create batches or sync against the main chain.
> Add SafeMode

- api/get_user_states.go
- main/jsonrpc.go
- storage/database.go
- storage/storage.go
Example trace:
above, most of the spans are barely visible because they pale in comparison to the long mempool scan.
below is what this looks like once we cache the c2t balances:
> instrument hubble_getUserStates

- deploy/hubble/templates/ingress.yaml
- deploy/hubble/values.yaml
This PR adds production.hubble.worldcoin-distributors.com and ability to add multiple hosts within one Ingress manifest
> Add additional domain for hubble-commander

- Makefile
- api/get_user_states.go
- api/mempool_test.go
- commander/commander.go
- storage/mempool.go
- storage/mempool_test.go
`hubble_getUserStates` is extremely slow and prone to latency spikes because it scans the entire mempool looking for the single transaction which sent a c2t to this pubkey. This PR builds a materialized view and will make these calls much cheaper.
Remaining work:
Future work (must happen before we disable Safe Mode):
> materialize pending pubkey balance

- api/admin/mempool.go
- api/get_user_states.go
- api/mempool_test.go
- models/dto/user_state.go
- models/public_key.go
- storage/mempool.go
- storage/mempool_test.go
users are reporting some claims transactions are not appearing in their wallet balances, these two additional `admin_*` methods will allow me to figure out which users are experiencing problems
> add admin endpoints to debug pending pubkey inconsistencies

- .github/workflows/build-test-deploy.yml
- deploy/hubble/values-stage.yaml
- deploy/hubble/values.yaml
Requests and limits are the mechanisms Kubernetes uses to control resources such as CPU and memory. Requests are what the container is guaranteed to get. If a container requests a resource, Kubernetes will only schedule it on a node that can give it that resource. Limits, on the other hand, make sure a container never goes above a certain value.
Production resources were set based on the current configuration running on the cluster.
Additionally, I move all stage values to a separate values file. The change can be checked using 
```
helm upgrade hubble-commander ./deploy/hubble --install --namespace hubble-commander --values ./deploy/hubble/values-stage.yaml --debug --dry-run
```
Update Aug 30, change production resources after we stabilize the service
> Set Kubernetes resource values
